### ISSUE TITLE
Distinguishing Schnorr signature

### ISSUE THREAD

**Issue by jae-cuz** [adrianmcli/summer-contribution-program#4]
### Summary

Schnorr signature based on traditional DLP and ECDLP are not distinguished.

### Location

- Module Name: Module 3
- Section/Step: Schnorr Signatures

### Proposed Correction

Schnorr signature was originally published based on traditional Discrete Logarithm Problem. EC(Elliptic Curve)-Schnorr was introduced later.
These two seems not to be distinguished strictly in several materials. Among 5 links of Schnorr signature in Module 3, two links describe DLP version while other links describe EC version.

Erasing DLP links would be one solution. 
However I suggest the way to move DLP-Schnorr signature to Module 2, as we introduced only one digital signature scheme(DSA) in Module 2. (Historically, DSA is proposed with intent to avoid patent issue of original Schnorr signature.)

Please let me know if you have other opinion, and thanks for your hard work writing these helpful materials! 😄 

### Screenshots (if applicable)

![image](https://github.com/adrianmcli/summer-contribution-program/assets/49219390/8b0d2587-68e4-4bc3-8169-e81e727a0487)

### Additional Context
[schnorr](https://blog.costan.ro/post/2019-06-19-schnorr/) vs [ec-schnorr](https://blog.costan.ro/post/2019-06-25-ec-schnorr/)

**Comment by adrianmcli** [comment]
@jae-cuz Thank you for this issue! This is a great point and I think your recommendation makes a lot of sense. Looking forward to seeing a PR with your suggested changes.

**Comment by adrianmcli** [comment]
Fixed by #6
